### ISSUE TITLE
Key source

### ISSUE THREAD

**Issue by 89z** [compenguy/panharmonicon#1]
I am trying to find the source of this key:

https://github.com/compenguy/panharmonicon/blob/202078c7ffe2cb583ef2514d0a4a7f79fa812ddd/src/pandora.rs#L29

added here:

https://github.com/compenguy/panharmonicon/commit/d65f450f527ae29065afde645b851724acd7159e

**Comment by compenguy** [comment]
I got it from here: https://6xq.net/pandora-apidoc/json/partners/

How they determined it, I have no idea.

Are you writing your own client? Or is this related to a fix, change, or feature in panharmonicon?

**Comment by 89z** [comment]
Yeah, I wrote my own:

https://github.com/89z/mech/tree/master/pandora

For some reason, I couldnt find a single implementation online, that supports the `onDemand.getAudioPlaybackInfo` method. If you know of one, or want to implement it here, I think it would be useful.

**Comment by compenguy** [comment]
It probably wouldn't be hard to work out.

If you look at https://6xq.net/pandora-apidoc/rest/endpoints/, it lists
* /v1/ondemand/getAudioPlaybackInfo
* /v1/ondemand/getReplayTrack
* 
and it documents the [getReplayTrack endpoint](https://6xq.net/pandora-apidoc/rest/ondemand/#rest-v1-ondemand-getreplaytrack). So getAudioPlaybackInfo probably takes a very similar set of parameters to getReplayTrack. After that, it's just a matter of picking out the interesting parts of the response.

I might take a look at that later this week, since I have holidays coming up and won't be tied up with work.

**Comment by 89z** [comment]
Found it:

~~~java
com\pandora\constants\PandoraConstants.java
8:    public static final byte[] b = "6#26FRL$ZWD".getBytes(Charset.defaultCharset());
~~~

https://github.com/skylot/jadx
